/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f2f4f6',
        'primary-fixed': '#e1e1f5',
        'on-primary-fixed-variant': '#444656',
        'primary-container': '#191b29',
        'on-secondary-container': '#57657b',
        'surface-container-highest': '#e0e3e5',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#008cc7',
        'secondary-container': '#d5e3fd',
        'tertiary-fixed': '#c9e6ff',
        'surface-dim': '#d8dadc',
        'on-tertiary-fixed': '#001e2f',
        'tertiary-fixed-dim': '#89ceff',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'secondary-fixed': '#d5e3fd',
        'on-primary-fixed': '#191b29',
        'inverse-on-surface': '#eff1f3',
        'on-secondary-fixed-variant': '#3a485c',
        outline: '#77767d',
        'tertiary-container': '#001e2f',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#46464c',
        secondary: '#515f74',
        'on-secondary': '#ffffff',
        'surface-tint': '#5c5d6e',
        'error-container': '#ffdad6',
        'outline-variant': '#c7c5cc',
        surface: '#f7f9fb',
        tertiary: '#000000',
        'surface-container': '#eceef0',
        'on-primary-container': '#818295',
        'on-error': '#ffffff',
        'surface-variant': '#e0e3e5',
        'primary-fixed-dim': '#c5c5d9',
        'on-tertiary-fixed-variant': '#004c6e',
        'secondary-fixed-dim': '#b9c7e0',
        error: '#ba1a1a',
        'inverse-primary': '#c5c5d9',
        'inverse-surface': '#2d3133',
        'surface-bright': '#f7f9fb',
        'on-secondary-fixed': '#0d1c2f',
        background: '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        primary: '#000000',
        'on-error-container': '#93000a',
        'on-surface': '#191c1e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        base: '4px',
        sm: '8px',
        md: '16px',
        xl: '48px',
        'margin-desktop': '40px',
        xs: '4px',
        lg: '24px',
        'margin-mobile': '16px',
        'container-padding': '24px',
      },
      fontFamily: {
        'anonymous': ["'Anonymous Pro'", 'monospace'],
        'body-md': ['Inter'],
        'headline-sm': ['Hanken Grotesk'],
        'body-lg': ['Inter'],
        'label-md': ['JetBrains Mono'],
        'headline-lg': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Hanken Grotesk'],
        'label-sm': ['JetBrains Mono'],
        'headline-md': ['Hanken Grotesk'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'headline-lg': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-lg-mobile': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-sm': [
          '10px',
          { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'headline-md': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      keyframes: {
        heartbeat: {
          '0%': { transform: 'scale(1)' },
          '15%': { transform: 'scale(1.1)' },
          '30%': { transform: 'scale(1)' },
          '45%': { transform: 'scale(1.1)' },
          '60%': { transform: 'scale(1)' },
          '100%': { transform: 'scale(1)' },
        },
        'ekg-ripple': {
          '0%': { transform: 'scale(0.8)', opacity: '0.6' },
          '15%': { transform: 'scale(1.5)', opacity: '0' },
          '30%': { transform: 'scale(1)', opacity: '0' },
          '45%': { transform: 'scale(1.5)', opacity: '0' },
          '100%': { transform: 'scale(0.8)', opacity: '0' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        heartbeat: 'heartbeat 2s infinite ease-in-out',
        'ekg-ripple': 'ekg-ripple 2s infinite ease-out',
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
      },
    },
  },
  plugins: [],
};
